### ISSUE TITLE
Chapter 7 page 207 variable "datafile" declaration and calling

### ISSUE THREAD

**Issue by wamiqraza** [PacktPublishing/Practical-Data-Science-with-Python#2]
In chapter 7 on page 207 the variable are decleare as:

`
datafile = 'https://docs.misoenergy.org/marketreports/20210203_mom.xlsx'
mom_data = urlopen(datafile_url).read()
print(mom_data[:20])
`

In theory it should be:
`
datafile_url= 'https://docs.misoenergy.org/marketreports/20210203_mom.xlsx'
mom_data = urlopen(datafile_url).read()
print(mom_data[:20])
`

I have check the cooresponding ipynb file on github its correct there. The updates will help in correction for next version.

**Comment by nateGeorge** [comment]
Thanks for bringing this to my attention! Good catch.

**Comment by wamiqraza** [comment]
Welcome @nateGeorge
