### ISSUE TITLE
Append not working in new version pandas

### ISSUE THREAD

**Issue by Frankocke** [PacktPublishing/Practical-Data-Science-with-Python#3]
the code on page 104 is not working:

test_df = itunes_df.copy()
test_df = test_df.append(itunes_df.loc[3502])
test_df.loc[3502]

I think this must be:

test_df = itunes_df.copy()
example_row = itunes_df.loc[[3502]]
test_df = concat([test_df, example_row])
test_df.loc[3502]

**Comment by nateGeorge** [comment]
Hmm, it doesn't look like append has been deprecated. I wonder if indexing the same way you did for concat works:

`test_df = test_df.append(itunes_df.loc[[3502]])`

It may be that the single set of square brackets returns a series, but the double set of brackets returns a dataframe.

**Comment by Frankocke** [comment]
Hi, 

DataFrame.append() and Series.append() have been deprecated and will be removed in a future version. Use [pandas.concat()](https://pandas.pydata.org/docs/dev/reference/api/pandas.concat.html#pandas.concat) instead ([GH 35407](https://github.com/pandas-dev/pandas/issues/35407)).

this code will do the job:

test_df = itunes_df.copy()
test_df = pd.concat([test_df, itunes_df.loc[[3502]]])

**Comment by nateGeorge** [comment]
Ah sorry, my mistake; thanks for the solution.

**Comment by Frankocke** [comment]
The same issue occurs on page 196 chapter 6:
full_forecast_df = full_forecast_df.append(forecast_df)

has to be changed in:
full_forecast_df = pd.concat([full_forecast_df, forecast_df])
