### ISSUE TITLE
Practical-Data-Science-with-Python(2021) code not correct

### ISSUE THREAD

**Issue by Frankocke** [PacktPublishing/Practical-Data-Science-with-Python#4]
Chapter 5 page 165
top_3_countries = sql_df.groupby('BillingCountry').sum(). sort_values(by='Total', ascending=False)[:3].index.values

gb = sql_df[sql_df['BillingCountry'].isin(top_3_countries)]. \
groupby([pd.Grouper(freq='M'), 'BillingCountry']).sum(). \
groupby(level=-1).cumsum()

Code above gives an error, pandas can only sum numeric columns

Working code:
top_3_countries = sql_df.groupby('BillingCountry').sum(numeric_only=True). sort_values(by='Total', ascending=False)[:3].index.values

gb = sql_df[sql_df['BillingCountry'].isin(top_3_countries)]. \
groupby([pd.Grouper(freq='M'), 'BillingCountry']).sum(). \
groupby(level=-1).cumsum(numeric_only=True)

**Comment by nateGeorge** [comment]
Thanks. I assume this is another pandas change/deprecation actually. I'm pretty sure what I intended there was value counts per month for each country, so it should be count() instead of sum().

**Comment by Frankocke** [comment]
Ok, i am gonna try that, thanks.
